# ----------------------------------------
# 1. APPLICATION SETUP
# ----------------------------------------
spring.application.name=profile-service
server.port=8080

# ----------------------------------------
# 2. MONGODB ATLAS CONNECTION
# ----------------------------------------
# Replace <password> with your real password!
# Replace 'cluster0.abcde.mongodb.net' with your actual cluster address from Step 2
spring.data.mongodb.uri=mongodb+srv://vikrantkumar_db_user:7uAv2YeLl5hbT22s@devproject.vcy7mop.mongodb.net/profile_service_db?retryWrites=true&w=majority

# Automatically create indexes (like unique username)
spring.data.mongodb.auto-index-creation=true

# ----------------------------------------
# 3. DEBUGGING (Optional)
# ----------------------------------------
# See the exact queries Spring sends to Atlas
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG