package com.snapitt.backend_service.modules.auth.model;

import lombok.Builder;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.Instant;

/**
 * OtpEntity - One-Time Password Authentication Model
 *
 * Temporary credentials generated during password reset flow.
 * Single-use codes sent to user email for verification.
 *
 * Lifecycle:
 * 1. User initiates forgot-password → initForgotPassword() creates OtpEntity
 * 2. OTP code generated (6 random digits) and stored in database
 * 3. User receives OTP via email (currently prints to console in development)
 * 4. User submits OTP + password → verifyOtp() validates
 * 5. User resets password → resetPassword() updates AuthEntity and deletes OtpEntity
 *
 * MongoDB Collection: "otps"
 * Indexes:
 * - email (regular): Allows fast lookup of most recent OTP per email
 * - Auto-delete: No TTL index (manual deletion on successful reset)
 *
 * Constraints:
 * - email is required and indexed (not a foreign key, used as search parameter)
 * - code is required (6-digit string)
 * - expiresAt is required (must be within 5 minutes of creation)
 *
 * Security Model:
 * - Short-lived: 5-minute validity window
 * - Not unique: Multiple OTPs can exist per email (old, new)
 * - Rate limited: No explicit rate limiting (apply at API layer)
 * - Brute-forceable: 1 million possibilities (6 digits) - requires rate limiting
 * - Not user-specific: Associated by email, not UserEntity ID
 *
 * Design Decisions:
 * - No user ID reference: Avoids tying OTP to account before verification
 * - Stored in separate collection: Keeps auth credentials separate
 * - Manual deletion: Gives flexibility for audit/recovery scenarios
 * - Instant type: Ensures server-side time, prevents client-side clock manipulation
 *
 * Future Improvements:
 * - Add TTL index for automatic cleanup of expired OTPs
 * - Add attempt counter to prevent brute force
 * - Store used OTP codes for audit trail (currently deleted)
 * - Add IP address for security monitoring
 *
 * @see AuthService#initForgotPassword(ForgotPasswordInitRequest)
 * @see AuthService#verifyOtp(VerifyOtpRequest)
 * @see AuthService#resetPassword(ResetPasswordRequest)
 * @since 1.0.0
 */
@Data
@Builder
@Document(collection = "otps")
public class OtpEntity {
    /**
     * Unique primary key (MongoDB ObjectId).
     * Auto-generated by MongoDB.
     * Used for document identification and deletion.
     * Format: 24-character hexadecimal string.
     */
    @Id
    private String id;

    /**
     * User's email address.
     * Used to identify which user requested password reset.
     * Indexed for fast lookup of recent OTPs per email.
     * Not a foreign key, searched by value only.
     *
     * Properties:
     * - Required: Cannot be null
     * - Not unique: Multiple OTPs can exist per email (previous + new)
     * - Format: Valid email address (validated by ForgotPasswordInitRequest)
     *
     * Query pattern: SELECT * FROM otps WHERE email = ? ORDER BY expiresAt DESC LIMIT 1
     *
     * @see ForgotPasswordInitRequest#email
     */
    @Indexed
    private String email;

    /**
     * One-time password code.
     * 6-digit decimal string sent to user via email.
     * User submits this code during password reset verification.
     *
     * Properties:
     * - Format: Decimal digits only (000000-999999)
     * - Length: Always 6 characters (leading zeros preserved as string)
     * - Generation: new Random().nextInt(999999), formatted as %06d
     * - Uniqueness: Not guaranteed (statistically rare collision)
     * - Comparison: Exact string match via equals()
     *
     * Example codes:
     * - 000000 through 999999
     * - String representation: "123456", "000789", "012345"
     *
     * Validation:
     * - Exact match: code.equals(submittedCode)
     * - No partial credit: Entire 6-digit code must match
     * - Case sensitive: N/A (decimal only), numeric comparison
     *
     * @see AuthService#initForgotPassword(ForgotPasswordInitRequest)
     * @see AuthService#verifyOtp(VerifyOtpRequest)
     */
    private String code;

    /**
     * Expiration timestamp (UTC).
     * Indicates when this OTP becomes invalid.
     * Set to Instant.now().plusSeconds(300) during creation (5 minutes).
     *
     * Properties:
     * - Type: Instant (nanosecond precision, UTC timezone)
     * - Duration: Exactly 300 seconds (5 minutes) from creation
     * - Immutable: Changed only via manual updates (not auto-updating)
     * - Server-side: Set by server, prevents client manipulation
     *
     * Validation:
     * - Expired if: Instant.now().isAfter(expiresAt)
     * - Check performed in verifyOtp(): returns OTP_EXPIRED if expired
     * - No grace period: Hard cutoff at 5 minutes
     *
     * Cleanup:
     * - Manual deletion: OTP deleted after successful resetPassword()
     * - No TTL index: Expired OTPs remain in database indefinitely (future improvement)
     * - Audit trail: Keeping deleted OTPs aids in security investigations
     *
     * @see AuthService#verifyOtp(VerifyOtpRequest)
     */
    private Instant expiresAt;
}