package com.snapitt.backend_service.modules.event.model;

public enum EventType {
    POST_CREATED,
    STORY_CREATED,
    POST_LIKED,
    POST_UNLIKED,
    POST_DISLIKED,
    COMMENT_CREATED,
    COMMENT_DELETED,
    FOLLOW_REQUESTED,
    FOLLOW_ACCEPTED,
    FOLLOW_REJECTED,
    FOLLOW_REQUEST_WITHDRAWN,
    UNFOLLOWED,
    POST_DELETED,
    STORY_DELETED
}
